name: ASR_Project
model:
  sample_rate: 16000
  labels:  # Definizione globale di etichette
    - avanti
    - indietro
    - sinistra
    - destra
    - cammina
    - corri
    - fermo
    - salta
    - vola
    - su
    - giu
    - pausa
    - continua
    - esci

  preprocessor:
    cls: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    params:
      sample_rate: 16000
      window_size: 0.02
      window_stride: 0.01
      n_fft: 320
      features: 64
      normalize: "per_feature"

  encoder:
    cls: nemo.collections.asr.modules.ConvASREncoder
    params:
      jasper:
        - filters: 1024
          repeat: 2
          kernel: [13]
          stride: [1]
          dilation: [1]
          dropout: 0.6
          separable: true
          residual: true
      activation: "relu"
      feat_in: 64

  decoder:
    cls: nemo.collections.asr.modules.ConvASRDecoderClassification
    params:
      feat_in: 1024
      num_classes: 14

  train_ds:
    manifest_filepath: "/home/giolinux/NLP_Project/train_manifest.json"
    batch_size: 32
    shuffle: true
    num_workers: 4
    sample_rate: 16000
    labels:  # Definizione locale per train_ds
      - avanti
      - indietro
      - sinistra
      - destra
      - cammina
      - corri
      - fermo
      - salta
      - vola
      - su
      - giu
      - pausa
      - continua
      - esci

  validation_ds:
    manifest_filepath: "/home/giolinux/NLP_Project/val_manifest.json"
    batch_size: 16
    shuffle: false
    num_workers: 4
    sample_rate: 16000
    labels:  # Definizione locale per validation_ds
      - avanti
      - indietro
      - sinistra
      - destra
      - cammina
      - corri
      - fermo
      - salta
      - vola
      - su
      - giu
      - pausa
      - continua
      - esci

  optim:
    name: adamw
    lr: 0.0005  # Learning rate aumentato
    weight_decay: 0.01
    sched:
      name: CosineAnnealing
      min_lr: 1e-5


trainer:
  max_epochs: 100

  accelerator: gpu
  devices: 1