name: ASR_Project

model:
  sample_rate: 16000
  labels: 
    - avanti
    - indietro
    - sinistra
    - destra
    - cammina
    - corri
    - fermo
    - salta
    - vola
    - su
    - giu
    - pausa
    - continua
    - esci

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: "per_feature"
    window_size: 0.02
    sample_rate: 16000
    window_stride: 0.01
    window: "hann"
    features: 68
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    stft_conv: false

  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: 68
    activation: relu
    conv_mask: true
    jasper:
      # Strati di base (rimangono invariati)
      - filters: 64
        repeat: 1
        kernel: [11]
        stride: [1]
        dilation: [1]
        dropout: 0.3
        residual: false

      - filters: 128
        repeat: 1
        kernel: [13]
        stride: [1]
        dilation: [1]
        dropout: 0.3
        residual: true

      # Layer aggiunti con i migliori iperparametri
      - filters: 64
        repeat: 1
        kernel: [9]
        stride: [1]
        dilation: [1]
        dropout: 0.31912931260383326
        residual: false
        activation: relu

      - filters: 64
        repeat: 1
        kernel: [9]
        stride: [1]
        dilation: [1]
        dropout: 0.31912931260383326
        residual: true
        activation: relu

  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoderClassification
    feat_in: 64  # Aggiornato in base all'ultimo layer con filters=64
    num_classes: 14

  train_ds:
    manifest_filepath: "/home/giova/NLP/NLP_Project-main/train_manifest_augmented.json"
    batch_size: 64  # Aggiornato per usare il best param
    shuffle: true
    num_workers: 4
    sample_rate: 16000
    labels: 
      - avanti
      - indietro
      - sinistra
      - destra
      - cammina
      - corri
      - fermo
      - salta
      - vola
      - su
      - giu
      - pausa
      - continua
      - esci

  validation_ds:
    manifest_filepath: "/home/giova/NLP/NLP_Project-main/val_manifest.json"
    batch_size: 32
    shuffle: false
    num_workers: 8
    pin_memory: true
    sample_rate: 16000
    labels:
      - avanti
      - indietro
      - sinistra
      - destra
      - cammina
      - corri
      - fermo
      - salta
      - vola
      - su
      - giu
      - pausa
      - continua
      - esci

  optim:
    name: "adamw"
    lr: 0.000751397140102378  # Aggiornato con il miglior learning rate
    weight_decay: 0.0001
    sched:
      name: "CosineAnnealing"
      warmup_steps: 500

trainer:
  gradient_clip_val: 0.1
  max_epochs: 50
  accelerator: "gpu"
  devices: 1
  precision: 16
