name: ASR_Project

model:
  sample_rate: 16000
  labels: 
    - avanti
    - indietro
    - sinistra
    - destra
    - cammina
    - corri
    - fermo
    - salta
    - vola
    - su
    - giu
    - pausa
    - continua
    - esci

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: "per_feature"
    window_size: 0.02
    sample_rate: 16000
    window_stride: 0.01
    window: "hann"
    features: 64
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    stft_conv: false


  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: 64  # Numero di feature di input del preprocessor
     activation: relu
    conv_mask: true
    jasper:  # Struttura base dell'encoder
      - filters: 256
        repeat: 1
        kernel: [11]
        stride: [1]
        dilation: [1]
        dropout: 0.3
        residual: false
      - filters: 256
        repeat: 1
        kernel: [13]
        stride: [1]
        dilation: [1]
        dropout: 0.3
        residual: true

  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoderClassification
    feat_in: 256  # Deve corrispondere al numero di filtri dell'ultimo livello dell'encoder
    num_classes: 14

  train_ds:
    manifest_filepath: "/home/giova/NLP/NLP_Project-main/train_manifest_augmented.json"
    batch_size: 32  # Configurabile tramite Optuna
    shuffle: true
    num_workers: 4
    sample_rate: 16000
    labels: 
      - avanti
      - indietro
      - sinistra
      - destra
      - cammina
      - corri
      - fermo
      - salta
      - vola
      - su
      - giu
      - pausa
      - continua
      - esci

  validation_ds:
    manifest_filepath: "/home/giova/NLP/NLP_Project-main/val_manifest.json"
    batch_size: 32
    shuffle: false
    num_workers: 8
    pin_memory: true
    sample_rate: 16000
    labels:
      - avanti
      - indietro
      - sinistra
      - destra
      - cammina
      - corri
      - fermo
      - salta
      - vola
      - su
      - giu
      - pausa
      - continua
      - esci

  optim:
    name: "adamw"  # Ottimizzatore AdamW
    lr: 0.0001  # Configurabile tramite Optuna
    weight_decay: 0.0001  # Fisso, utile per evitare overfitting
    sched:
      name: "CosineAnnealing"
      warmup_steps: 500  # Step iniziali per il warm-up del learning rate

trainer:
  gradient_clip_val: 0.1
  max_epochs: 50  # Configurabile per training rapido durante il tuning
  accelerator: "gpu"
  devices: 1
  precision: 16  # Mixed precision per ottimizzare memoria e velocità

exp_manager:
  exp_dir: ./experiments
  name: asr_experiment
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_epoch_top@1
    mode: max
    save_top_k: 3
    filename: 'asr-{epoch:02d}-{val_epoch_top@1:.2f}'
